spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tmsdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.tms: WARN